name: Send Release Email with APK

on:
  release:
    types: [published]

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Download latest release asset
      run: |
        ASSET_URL=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.assets[0].browser_download_url')
        wget -O app-release.apk "$ASSET_URL"
      shell: bash

    - name: Generate Email HTML
      run: |
        sed -e "s|{{TAG_NAME}}|${{ github.event.release.tag_name }}|g" \
            -e "s|{{REPO_NAME}}|${{ github.repository }}|g" \
            -e "s|{{CHANGELOG}}|${{ github.event.release.body }}|g" \
            -e "s|{{GITHUB_RELEASE_URL}}|${{ github.event.release.html_url }}|g" \
            release_email_template.html > email.html

    - name: Send email with attachment
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.office365.com
        server_port: 587
        username: ${{ secrets.OUTLOOK_USERNAME }}
        password: ${{ secrets.OUTLOOK_PASSWORD }}
        subject: "🚀 New Release: ${{ github.event.release.tag_name }}"
        to: ${{ secrets.EMAIL_RECIPIENTS }}
        from: "${{ secrets.OUTLOOK_USERNAME }}"
        content_type: text/html
        content_transfer_encoding: quoted-printable
        attachments: "app-release.apk"
        html_body: file://email.html
