name: Send Release Email

on:
  release:
    types: [published]  # Triggers only when a release is published

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
    - name: Send email via Outlook
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.office365.com
        server_port: 587
        username: ${{ secrets.OUTLOOK_USERNAME }}
        password: ${{ secrets.OUTLOOK_PASSWORD }}
        subject: "🚀 New Release: ${{ github.event.release.tag_name }}"
        to: gregorius.lai@sinarmas-agri.com
        from: "${{ secrets.OUTLOOK_USERNAME }}"
        content_type: text/html
        body: |
            <html>
            <body style="font-family: Arial, sans-serif; color: #333;">
              <h2>🎉 New Release: <b>${{ github.event.release.tag_name }}</b></h2>
              <p><b>Repository:</b> ${{ github.repository }}</p>
              <p><b>Version:</b> ${{ github.event.release.tag_name }}</p>
              <p><b>Changelog:</b> ${{ github.event.release.body }}</p>
              <p><b>Download:</b> <a href="${{ github.event.release.html_url }}">Click here</a></p>
            </body>
            </html>
